### ISSUE TITLE
Support prefetch per handler

### ISSUE THREAD

**Issue by alkiskal** [Workable/rabbit-queue#23]
It is useful to have handlers with different prefetch values.

https://github.com/Workable/rabbit-queue/blob/1e58da7953b941f0076cc77c4d7da23966108c0f/ts/rabbit.ts#L70

Right now this is not possible since every connection supports only one channel (where the prefetch is set). The logical solution would be to support an array of channels (as many as different prefetches), baring in mind the below: 
- https://www.cloudamqp.com/blog/2018-01-19-part4-rabbitmq-13-common-errors.html
- https://www.cloudamqp.com/blog/2019-11-13-the-relationship-between-connections-and-channels-in-rabbitmq.html

**Comment by nikostoulas** [comment]
Implemented in 4.7.0
