### ISSUE TITLE
Safe shutdown?

### ISSUE THREAD

**Issue by kingpoststudio** [Workable/rabbit-queue#29]
First off - its great to see a maintained abstraction layer for RMQ, and I appreciate your work getting this out for other teams to use.

I'm using a module called 'rabbot' within several workers to manage our queues because it provides a way to safely shutdown whenever we redeploy. This allows any in-process messages to be ack'd, nack'd or rejected before the process is exited. Each of them listens for SIGINT or SIGTERM and calls rabbot.shutdown to ensure that these messages are not lost. However, we're considering deprecating its use since its been over two years since its last update.

https://github.com/arobson/rabbot/blob/master/src/index.js
```js
Broker.prototype.shutdown = function () {
  return this.closeAll(true)
    .then(() => {
      this.clearAckInterval();
    });
};
```

Is there a way to implement this within rabbit-queue? Granted, I've lightly looked over the documentation. I will continue to do my due diligence but in order for my team to fully adopt this module, a way to control the shutdown process would be a big win.

**Comment by grantsru** [comment]
Posting in this thread to watch on my personal acct.

**Comment by nikostoulas** [comment]
Hi @kingpoststudio thanks for you nice words.

Currently rabbit-queue doesn't support graceful shutdowns. However you will not loose messages during shutdowns. Messages that aren't ack'd or nack'd during a shutdown will be left to the queue for the next process to re-process them. This might end up processing a message twice.

So to better understand your usage, you care about not processing twice messages during graceful shutdowns is that right? 
From a quick look rabbot supports batch acks. Rabbit-queue does not so either you handle acks like in the example: 
```js
rabbit
  .createQueue('queueName', { durable: false }, (msg, ack) => {
    console.log(msg.content.toString());
    **ack(null, 'response')**;
  })
```
Or you can use the higher abstraction of Handler and let rabbit-queue do that for you when you return a value eg:
```js
class DemoHandler extends BaseQueueHandler {
  handle({ msg, event, correlationId, startTime }) {
    console.log('Received: ', event);
    console.log('With correlation id: ' + correlationId);
    return Promise.resolve('reply'); 
// ack will be called after this here https://github.com/Workable/rabbit-queue/blob/master/ts/base-queue-handler.ts#L106
  }

  afterDlq({ msg, event }) {
    // Something to do after added to dlq
  }
}
```

Do these make any sense to you?

**Comment by grantsru** [comment]
@nikostoulas - makes sense, yes. Thanks for taking the time to answer. I think I can manage to make the module work for my needs.

**Comment by nikostoulas** [comment]
Closing this as it seems resolved. If you face any other issues, please open another issue.
