### ISSUE TITLE
Nacking a message

### ISSUE THREAD

**Issue by flpelluz** [Workable/rabbit-queue#32]
Hello! 

First off, thanks for the library. Great and simple abstraction. It's helping us quite a bit! 

What would be the way to nack messages? From your comment to this [issue](https://github.com/Workable/rabbit-queue/issues/29) I take that it's possible, but I haven't figured still how.

Thanks!

**Comment by nikostoulas** [comment]
Hi @flpelluz, thanks for your kind words and support.

Nack support is not built in the library but you can easily do it.
Using a Readme example: 
```rabbit
  .createQueue('queueName', { durable: false }, (msg, ack) => {
    console.log(msg.content.toString());
    rabbit.consumeChannel.nack(msg);
  })```
See the [amqplib](http://www.squaremobius.net/amqp.node/channel_api.html#channel_nack) documentation for details about nack: 

Note that if you just want to move messages to dlqs you can use [BaseQueueHandler](https://github.com/Workable/rabbit-queue#advanced-usage-with-basequeuehandler-will-add-to-dlq-after-3-failed-retries) that does that. Throwing an error inside handle will do the error handling for you.

**Comment by flpelluz** [comment]
@nikostoulas thanks for the quick reply! I figured it now. We are still on the 4.7.1 version where there is no consumeChannel function on the rabbit object.

We have implemented already the dlq logic and it is working fine. To it, we move invalid messages. However, for valid messages, we don't want them to be moved to the dlq. Therefore, I'm implementing an exponential backoff retry logic that if no success after a while, it should nack the message so that it gets re-queued and we try with the next one instead. And, it continues all time like this. 

Perhaps, this could be a cool functionality to add to the library :)

All clear now, you can close this issue. Cheers!
