### ISSUE TITLE
Establish two connection on RabbitMQ

### ISSUE THREAD

**Issue by niteshtripathi1234** [Workable/rabbit-queue#35]
import { Rabbit } from 'rabbit-queue';
 RabbitQueue.rabbitConnection =
                new Rabbit(config.rabbitMQUrl, { scheduledPublish: false });

I am trying to establish a connection with RabbitMQ it's able to establish a connection successfully but it established a two connection(socket) on RbbitMQ.

Please let me know what I am doing wrong?

**Comment by nikostoulas** [comment]
Hi @niteshtripathi1234 ,

By default two connections are established one for producers and one for consumers. This is the case as of the latest major version of rabbit-queue. You can see the pr: https://github.com/Workable/rabbit-queue/pull/26 for more details.

Does this help?

**Comment by niteshtripathi1234** [comment]
Hi Nikos,
Is there any way to open only producers channel not consumer channel.

Thanks and regards
Nitesh

**Comment by nikostoulas** [comment]
Unfortunately this is not configurable yet. Does this cause you issues? Can you share more about your use case?

**Comment by niteshtripathi1234** [comment]
Hi Nikos,
My use-case are -
1- First Services a produce a SMS and push to queue.
2- Second Services consume the sms and send a sms.

so, i do not need a consumer channel on that service.

**Comment by nikostoulas** [comment]
Ok makes sense. Do you have a connection limitation? If not the extra connection shouldn't be an issue for you.
If you do you could downgrade to v4 of the library until configuring consumer or producer channel is implemented.

**Comment by niteshtripathi1234** [comment]
Ok no problem, can you share me a example through which i can maintain a
long lived connection.

**Comment by nikostoulas** [comment]
You could use rabbit-queue 4.7.1. See https://github.com/Workable/rabbit-queue-stream-examples/blob/d462d8f241b3ea86ce9a89839fcee88d27f51e85/connect.js
You also need log4js for logging in this version.

**Comment by nikostoulas** [comment]
Closing this. @niteshtripathi1234 if you have other issues please open a new ticket.
