### ISSUE TITLE
some flag support are not there. 

### ISSUE THREAD

**Issue by kundan8239** [Workable/rabbit-queue#54]
As I can see lib does not support these two arguments' flags. 
1. x-overflow: 'reject-publish',  
2. 'x-queue-mode': 'lazy'

I have tried to update these flags here is my code but getting exception. 

`const { BaseQueueHandler, Rabbit } = require('rabbit-queue');
const rabbit = new Rabbit(process.env.RABBIT_URL || 'amqp://localhost', {
  prefetch: 1, //default prefetch from queue
  replyPattern: true, //if reply pattern is enabled an exclusive queue is created
  scheduledPublish: false,
  prefix: '', //prefix all queues with an application name
  socketOptions: {} // socketOptions will be passed as a second param to amqp.connect and from ther to the socket library (net or tls)
});

rabbit.on('connected', () => {
  //create queues, add halders etc.
  //this will be called on every reconnection too
  console.log("Rabbit-queue Rabbit-queue !!!");
});

rabbit.on('disconnected', (err = new Error('Rabbitmq Disconnected')) => {
  //handle disconnections and try to reconnect
  console.error(err);
  setTimeout(() => rabbit.reconnect(), 100);
});

class BatchBaseWorker extends BaseQueueHandler {
  constructor(queueName) {
    super(queueName, rabbit, {
      prefetch: 25,
      retries: 0,
      retryDelay: 1000,
      logEnabled: true,
      scope: 'SINGLETON',
      createAndSubscribeToQueue: true,
    });
    this.queueName = queueName;
  }

  async createQueues() {
    this.queue = await this.rabbit
      .createQueue(this.queueName, { ...this.getQueueOptions(), prefetch: this.prefetch,   maxLength: 25 }, (msg, ack) => {
        this.tryHandle(0, msg, ack).catch((e) => this.logger.error(e));
      })
      .catch((error) => this.logger.error(error));
      let queueOptions = { 
        arguments: {
        'x-overflow': 'reject-publish',
        'x-queue-mode': 'lazy'
      }}
     let res = await this.queue.channel.assertQueue(this.queueName, queueOptions);
     console.log(this.queue.options);
     console.log(res);
    this.dlq = await this.rabbit
      .createQueue(this.dlqName, this.getDlqOptions())
      .catch((error) => this.logger.error(error));
  }
}
new BatchBaseWorker('sauron_content');`

Exception message :   Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - inequivalent arg 'x-max-length' for queue 'sauron_content' in vhost '/': received '[{<<"type">>,longstr,<<"byte">>},{<<"value">>,byte,25}]' but current is '25'" 

package version : 5.4.1 

https://github.com/Workable/rabbit-queue/blob/master/ts/queue.ts#L54

**Comment by nikostoulas** [comment]
Hi @kundan8239 ,
the error is possibly due to the fact that the queue already exists in RabbitMQ but is not created with x-max-length:25.
Try deleting the queue if possible and recreating. 

A proper solution for the library to support extra arguments would be in queue.ts to also accept arguments and not overwrite them in [L54](https://github.com/Workable/rabbit-queue/blob/master/ts/queue.ts#L54). This way you could add your custom arguments in your application code by overwriting [getQueueOptions](https://github.com/Workable/rabbit-queue/blob/master/ts/base-queue-handler.ts#L58). If you have time to look into it, prs are welcome. If not we will add it in our backlog.

What you do will not work because you create the queue with some configuration and afterwards try to create it with different configuration.

**Comment by kundan8239** [comment]
tried your solution but had no luck here is the code with a snapshot. 

`const { BaseQueueHandler, Rabbit } = require('rabbit-queue');

const rabbit = new Rabbit(process.env.RABBIT_URL || 'amqp://localhost', {
  prefetch: 1, //default prefetch from queue
  replyPattern: true, //if reply pattern is enabled an exclusive queue is created
  scheduledPublish: false,
  prefix: '', //prefix all queues with an application name
  socketOptions: {} // socketOptions will be passed as a second param to amqp.connect and from ther to the socket library (net or tls)
});

rabbit.on('connected', () => {
  //create queues, add halders etc.
  //this will be called on every reconnection too
  console.log("Rabbit-queue Rabbit-queue !!!");
});

rabbit.on('disconnected', (err = new Error('Rabbitmq Disconnected')) => {
  //handle disconnections and try to reconnect
  console.error(err);
  setTimeout(() => rabbit.reconnect(), 100);
});

class BatchBaseWorker extends BaseQueueHandler {
  constructor(queueName) {
    super(queueName, rabbit, {
      prefetch: 25,
      retries: 0,
      retryDelay: 1000,
      logEnabled: true,
      scope: 'SINGLETON',
      createAndSubscribeToQueue: true,
    });
    this.queueName = queueName;
  }

  getQueueOptions() {
    const options = {
      durable: true,
      arguments: {
        'x-max-priority': 20,
        'x-max-length': 100,
        'x-overflow': 'reject-publish',
        'x-queue-mode': 'lazy'
      }
    }
    return {
      ...super.getQueueOptions(),
      ...options
    }
  }
}
new BatchBaseWorker('demo_one');
`
<img width="999" alt="Screenshot 2023-04-20 at 10 55 59 PM" src="https://user-images.githubusercontent.com/26499928/233442282-eb653a66-859d-487d-afda-bbaa594f621c.png">

**Comment by nikostoulas** [comment]
@kundan8239 rabbit-queue@5.5.0 is published on npm including your pr.
