### ISSUE TITLE
Special characters are escaped 

### ISSUE THREAD

**Issue by andrevus** [Workable/rabbit-queue#8]
I can't publish payload with new line characters, cause they automatically converted into string. 
This line is responsible for it:
https://github.com/Workable/rabbit-queue/blob/master/ts/exchange.ts#L16

**Comment by nikostoulas** [comment]
Hi @andrevus,

You need to JSON.parse the payload in the receiving part:
eg: 
```javascript
rabbit
  .createQueue('queueName', { durable: false }, (msg, ack) => {
    console.log(JSON.parse(msg.content.toString()));
    ack(null, 'response');
  })
  .then(() => console.log('queue created'));

// test 
Rabbit.getReply("queueName", "test \n\n\n\n\n test")
``` 

if you use BaseQueueHandler as described here: https://github.com/Workable/rabbit-queue#advanced-usage-with-basequeuehandler-will-add-to-dlq-after-3-failed-retries this will be done for you and event will be the JSON parsed. See here: https://github.com/Workable/rabbit-queue/blob/master/ts/baseQueueHandler.ts#L92

Does this resolve your issues?

**Comment by szoper** [comment]
I work with @andrevus so both of us encountered this issue.

No, that does not resolve the issue in any way. The receiving part is a generic microservice which should not rely on the fact, that only one of the senders uses JS library which hardcodes JSON payloads.  
Please fix this or at least make JSON.stringify optional.

**Comment by nikostoulas** [comment]
Hi @szoper,

I see your point. This library aims to make it easy to work with jsons over rabbitmq. The change you suggest is a backwards incompatible one. However, I can see the value of not stringifying strings and handling strings and jsons.
This could be added in the next major release of the library. Until then you could directly use ```rabbit.channel``` to publish messages the way you see fit.

**Comment by szoper** [comment]
Thanks for the explanation.  
I'm completely aware that such decision was one of your core assumptions about the design and the way people would use your library. Such change will definitely break compatibility with previous versions and deserves a major version bump.
I see a different but related issue - none of us was aware of this particular design feature when we were looking for RabbitMQ abstraction. You say that 

> This library aims to make it easy to work with jsons over rabbitmq

but this is not stated neither in project's description, nor in "About" section of README :)

Nevertheless, we've already used the workaround you also mention but we're looking forward to seeing a new major version.
